// ZipMaster configuration 1.79

//__ NO_SPAN - define to remove support for multi-part zip files
//{$DEFINE NO_SPAN}

//__ INTERNAL_SFX - define to include internal SFX support
{$DEFINE INTERNAL_SFX}

//__ ALLOW_2G - define to allow OnProgress to work with files > 2G
{$DEFINE ALLOW_2G}
                           
//__ USE_COMPRESSED_STRINGS - undefine to use ResourceStrings
{$Define USE_COMPRESSED_STRINGS}

//__ STATIC_LOAD_DELZIP_DLL - define to statically load dll
//{$DEFINE STATIC_LOAD_DELZIP_DLL}

//__ KEEP_BACKWARD - define to keep backward compatable
//{$DEFINE KEEP_BACKWARD}

(* ******* do not change beyong this point ****** *)
//{$INCLUDE '.\ZipVers.inc'}


